name: CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: make application.yml
        run: |
          mkdir -p ./src/main/resources
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml

      - name: Build with Gradle
        run: ./gradlew build -x test --parallel

      - name: Build Docker Image For Spring
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/modurang:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/modurang:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: EC2 Docker Run
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.LINUX_HOST }}
          username: ${{ secrets.LINUX_USERNAME }}
          key: ${{ secrets.LINUX_KEY }}
          script: |
            cd /
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker compose -f ./docker-compose.yml stop modurang
            docker compose -f ./docker-compose.yml rm -f modurang
            docker compose -f ./docker-compose.yml up modurang --pull always -d
            #docker compose -f ./docker-compose.yml up modurang --pull always -d
            #docker compose -f ./docker-compose.yml stop
            #docker compose -f ./docker-compose.yml up
